version: 2

before:
  hooks:
    - rustup default stable

builds:
  - id: "project-absence"
    builder: rust
    binary: project-absence
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      # These targets will have to use Docker or build themselves:
      #
      # This ones makes problems with Lua
      # - x86_64-apple-darwin
      #
      # This one has issues on Linux runners
      # - aarch64-apple-darwin
      #
      # This is not supported by Zig/zigbuild
      # - x86_64-pc-windows-msvc
      # - aarch64-pc-windows-msvc
    flags:
      - --release

archives:
  - formats: [tar.gz]
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
