[package]
name = "project-absence"
description = "👁️  Uncover the unseen"
version = "0.14.0"
license = "MIT"
readme = "README.md"
include = [
    "/Cargo.toml",
    "/LICENSE.md",
    "/README.md",
    "/TERMS_OF_USE.md",
    "/src/**",
]
repository = "https://github.com/kkrypt0nn/project-absence"
edition = "2024"

[features]
default = []
clipboard = ["dep:arboard"]

[dependencies]
arboard = { version = "=3.6.1", optional = true }
base64 = "=0.22.1"
chrono = "=0.4.44"
clap = { version = "=4.6.0", features = ["derive"] }
domain = { version = "=0.11.1", features = ["resolv-sync"] }
human_bytes = "=0.4.3"
memory-stats = "=1.2.0"
mlua = { version = "=0.11.6", features = ["lua54", "send", "vendored"] }
rand = "=0.10.0"
regex = "=1.12.3"
reqwest = { version = "=0.13.2", features = ["blocking", "json"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
simple-semaphore = "=1.0.0"
tangra = "=1.3.0"
toml = "=1.1.2"
x509-parser = "=0.18.1"
